# Config override for deployment
version: '3'

services:
  web:
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8088"
    - "traefik.frontend.rule=Host:codymaze.codemooc.org"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped
